[project]
name = "tools"
version = "0.1.0"
description = "convinience tools for valorant bot"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pystray>=0.19.5",
    "pywin32>=307",
    "rich>=13.9.2",
]
